platform:ios, ‘7.0’
pod 'MBProgressHUD', '~> 0.9.1'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'UIActivityIndicator-for-SDWebImage+UIButton', '~> 1.2'
pod 'MJRefresh', '~> 1.4.6'
pod 'CMPopTipView', '~> 2.2.0'
pod 'AIMTableViewIndexBar', '~> 0.1.1'
pod 'iOS-Slide-Menu', '~> 1.4.6'
pod 'REFrostedViewController', '~> 2.4.8'
pod 'SBJson4', '~> 4.0.1'
pod 'ZYQAssetPickerController', '~> 1.0.0'
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'AVOSCloudCrashReporting'